### PR TITLE
Plt#78 ability bugs

### LINKED ISSUE #78: Admin user cannot create new Site record.
@wonook due to Ability setup, cannot create new Site record. 
`      can :manage, Site,
          installation_id: @user.organization.installations.map { |a| a.id }
`

### PR DESCRIPTION
**Pull request by wonook**
Issue #78  - Bugs related to Ability.rb

1.Admin ability have been fixed to enable admins to create Sites that belong to their organization.
2.Added comments for the `ability.rb` file to clear out users' abilities.
3.Volunteers belong to a single site, but they have been given access to multiple sites. I've limited their access to the site they belong to only.
4.Superadmins now have access to any of the organizations.
5.Admins are able to view and edit the organization they belong to.

Author : @wonook - Won Wook SONG (wsong0512@gmail.com)

This pull request closes #78

### CODE REVIEW

File: app/models/ability.rb [hunk 1]
```diff
@@ -8,17 +8,24 @@ def initialize(user)
...
 
     if user.has_role? :superadmin
+      #Superadmins can do anything. They can also access the ActiveAdmin interface via http://the_site_address/admin
       can :manage, :all
       can :read, ActiveAdmin::Page, name: "Dashboard", namespace_name: :superadmin
 
     elsif user.has_role? :admin
+      #Admins all belong to an organization. They can manage Languages, Categories and Articles freely,
+      # but they can only manage the Installations, Sites, and Users that belong to their own organization.
       can :manage, [Language, Category, Article]
```
Comment (isuriupeksha) [inline app/models/ability.rb]: @wonook I think, admin can create organizations. If then, 
We have to update like this. `can :manage, [Language, Category, Article, Organization]`
I added above line to apply new templates.

Comment (wonook) [inline app/models/ability.rb]: Do you think an admin of a particular organization, say 'Peace Corps' should be able to create, edit, and destroy any `Organizations`, that are not 'Peace Corps'?

Comment (isuriupeksha) [inline app/models/ability.rb]: Ok, right. If admin is associated with an organization, it is fine. Then `super-admin` can only see the organizations list. But admin should be able to edit or update his organization name by using this controller, 

https://github.com/systers/language-translation/blob/develop/app/controllers/organizations_controller.rb

Comment (isuriupeksha) [inline app/models/ability.rb]: Also you need to add more test cases above cases. I cannot find more test cases for Organizations.

Comment (isuriupeksha) [inline app/models/ability.rb]: For example I have written articleController test for `admin` and `contributor`. 

https://github.com/systers/language-translation/blob/develop/test/controllers/contributor/articles_controller_test.rb#L11

Since we have at 4 roles, better to add at least one or two test cases.

**Comment by abelards** [comment]
:+1:

File: app/models/ability.rb (hunk 1 above)
Comment (wonook) [inline app/models/ability.rb]: Sure, that sounds much more reasonable. I'll make that happen like what I've done with sites in [this commit](https://github.com/systers/language-translation/commit/776ac63755d5455bec452dc68625f0bddff809e8). 

I'm planning to add and fix test cases all at once with another issue (#83).
